services:
  webserver:
    build: ./WebServer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  receiveserver:
    build: ./ReceiveServer
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - app-network

  calculation:
    build: ./CalculationModule
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: signal_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
